version: '3.8'

services:
  # PostgreSQL Database (Local Development)
  db:
    image: postgres:15-alpine
    container_name: nexcart_db_local
    environment:
      POSTGRES_DB: nexcart_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1872
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Django Backend (using local database)
  backend:
    build:
      context: ./nexcart_backend
      dockerfile: Dockerfile
    container_name: nexcart_backend_local
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-local-development-key
      - DATABASE_URL=postgres://postgres:1872@db:5432/nexcart_db
      - ALLOWED_HOSTS=localhost,127.0.0.1,backend
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://localhost:5173,http://frontend
    volumes:
      - media_files:/app/media
      - static_files:/app/staticfiles
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn --bind 0.0.0.0:8000 nexcart_backend.wsgi:application"

  # React Frontend
  frontend:
    build:
      context: ./nexcart-frontend-new
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://localhost:8000/api
    container_name: nexcart_frontend_local
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data:
  media_files:
  static_files:
