version: '3.8'

services:
  # Django Backend (using external Render database)
  backend:
    build:
      context: ./nexcart_backend
      dockerfile: Dockerfile
    container_name: nexcart_backend
    environment:
      - DEBUG=${DEBUG:-True}
      - SECRET_KEY=${SECRET_KEY:-django-insecure-default-key}
      - DATABASE_URL=${DATABASE_URL}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-localhost,127.0.0.1,backend}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS:-http://localhost:3000,http://localhost:5173,http://frontend}
      - STRIPE_PUBLIC_KEY=${STRIPE_PUBLIC_KEY:-}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY:-}
    volumes:
      - media_files:/app/media
      - static_files:/app/staticfiles
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn --bind 0.0.0.0:8000 nexcart_backend.wsgi:application"

  # React Frontend
  frontend:
    build:
      context: ./nexcart-frontend-new
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://localhost:8000/api
    container_name: nexcart_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  media_files:
  static_files:
