services:
  # Django Backend Web Service
  - type: web
    name: nexcart-backend
    env: python
    buildCommand: |
      cd nexcart_backend &&
      pip install -r requirements.txt &&
      python manage.py collectstatic --noinput
    startCommand: |
      cd nexcart_backend &&
      python manage.py migrate &&
      gunicorn --bind 0.0.0.0:$PORT --workers 3 nexcart_backend.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: nexcart-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: nexcart-backend.onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://nexcart-frontend.onrender.com
      - key: DJANGO_SETTINGS_MODULE
        value: nexcart_backend.settings
      - key: PYTHONPATH
        value: /opt/render/project/src/nexcart_backend
      - key: RENDER
        value: True

databases:
  - name: nexcart-db
    databaseName: nexcart_db
    user: nexcart_user
    plan: free
