name: Build and Push to Docker Hub

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master ]

env:
  BACKEND_IMAGE_NAME: nexcart-backend
  FRONTEND_IMAGE_NAME: nexcart-frontend

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Extract metadata for backend
      id: meta-backend
      uses: docker/metadata-action@v5
      with:
        images: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.BACKEND_IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Extract metadata for frontend
      id: meta-frontend
      uses: docker/metadata-action@v5
      with:
        images: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.FRONTEND_IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push backend image
      uses: docker/build-push-action@v5
      with:
        context: ./nexcart_backend
        file: ./nexcart_backend/Dockerfile
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta-backend.outputs.tags }}
        labels: ${{ steps.meta-backend.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build and push frontend image
      uses: docker/build-push-action@v5
      with:
        context: ./nexcart-frontend-new
        file: ./nexcart-frontend-new/Dockerfile
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta-frontend.outputs.tags }}
        labels: ${{ steps.meta-frontend.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Create docker-compose.hub.yml
      if: github.event_name != 'pull_request'
      run: |
        cat > docker-compose.hub.yml << EOF
        version: '3.8'
        
        services:
          backend:
            image: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.BACKEND_IMAGE_NAME }}:latest
            container_name: nexcart_backend_hub
            environment:
              - DEBUG=\${DEBUG:-False}
              - SECRET_KEY=\${SECRET_KEY}
              - DATABASE_URL=\${DATABASE_URL}
              - ALLOWED_HOSTS=\${ALLOWED_HOSTS:-localhost,127.0.0.1}
              - CORS_ALLOWED_ORIGINS=\${CORS_ALLOWED_ORIGINS:-http://localhost:3000}
              - STRIPE_PUBLIC_KEY=\${STRIPE_PUBLIC_KEY:-}
              - STRIPE_SECRET_KEY=\${STRIPE_SECRET_KEY:-}
            volumes:
              - media_files:/app/media
              - static_files:/app/staticfiles
            ports:
              - "8000:8000"
            command: >
              sh -c "python manage.py migrate &&
                     python manage.py collectstatic --noinput &&
                     gunicorn --bind 0.0.0.0:8000 nexcart_backend.wsgi:application"
        
          frontend:
            image: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.FRONTEND_IMAGE_NAME }}:latest
            container_name: nexcart_frontend_hub
            ports:
              - "3000:80"
            depends_on:
              - backend
        
        volumes:
          media_files:
          static_files:
        EOF

    - name: Upload docker-compose.hub.yml
      if: github.event_name != 'pull_request'
      uses: actions/upload-artifact@v4
      with:
        name: docker-compose-hub
        path: docker-compose.hub.yml
